services:
  - type: web
    name: email-aggregator-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://email-aggregator-backend.onrender.com

  - type: web
    name: email-aggregator-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ELASTICSEARCH_URL
        fromDatabase:
          name: elasticsearch
          property: connectionString
      - key: GOOGLE_AI_API_KEY
        sync: false

databases:
  - name: elasticsearch
    databaseName: elasticsearch
    plan: free